#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

######################################################################
# Dev image...
######################################################################
FROM preset/superset:dev

COPY ./requirements* ./docker/requirements* /app/

USER root
RUN cd /app \
    && pip install -e . \
    && pip install --no-cache -r requirements.txt -r requirements-dev.txt \
    && pip install --no-cache -r requirements-extra.txt \
    && pip install --no-cache -r requirements-local.txt || true

RUN apt update -y\
        && apt install -y build-essential libssl-dev libffi-dev python3-dev python3-pip rpm2cpio cpio unixodbc-dev wget libgssapi-krb5-2

RUN cd / \
        && wget http://package.mapr.com/tools/MapR-ODBC/MapR_Drill/MapRDrill_odbc_v1.3.22.1055/maprdrill-1.3.22.1055-1.x86_64.rpm \
        && rpm2cpio maprdrill-1.3.22.1055-1.x86_64.rpm | cpio -idmv && rm ./maprdrill-1.3.22.1055-1.x86_64.rpm

RUN pip install pyodbc
RUN pip install --ignore-installed git+https://github.com/drorspei/sqlalchemy-drill.git

COPY odbc.ini /home/superset/.odbc.ini
COPY odbcinst.ini /etc/odbcinst.ini
COPY data_sources.yaml /app/data_sources.yaml

RUN cd /app

USER superset
